name: Quality Assurance

on:
  pull_request:
  push:
    branches: [ 1.x ]
  schedule: [ { cron: '0 8 * * *' } ]

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        dependencies: [ locked, lowest, highest ]
        php-version: [ 7.4 , 8.0 ]
        operating-system: [ ubuntu-latest ]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          tools: composer:v2
          php-version: ${{ matrix.php-version }}
          ini-values: memory_limit=-1
        env:
          COMPOSER_TOKEN: ${{ secrets.PRIVATE_REPOSITORY_ACCESS }}

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Install tools
        uses: ramsey/composer-install@v2
        with:
          working-directory: ./tools

      - name: Tests
        run: composer test
        timeout-minutes: 2

  static-analyze:
    name: Static Analyze
    strategy:
      matrix:
        dependencies: [ locked ]
        php-version: [ 7.4 ]
        operating-system: [ ubuntu-latest ]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          tools: composer:v2
          php-version: ${{ matrix.php-version }}
          ini-values: memory_limit=-1
        env:
          COMPOSER_TOKEN: ${{ secrets.PRIVATE_REPOSITORY_ACCESS }}

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: Install tools
        uses: ramsey/composer-install@v2
        with:
          working-directory: ./tools

      - name: Static Analyze
        run: composer static:analyze
        timeout-minutes: 2

    mutation-tests:
      name: Mutation Tests
      strategy:
        matrix:
          dependencies: [ locked ]
          php-version: [ 7.4 ]
          operating-system: [ ubuntu-latest ]

      runs-on: ${{ matrix.operating-system }}

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install PHP
          uses: shivammathur/setup-php@v2
          with:
            coverage: pcov
            tools: composer:v2
            php-version: ${{ matrix.php-version }}
            ini-values: memory_limit=-1
          env:
            COMPOSER_TOKEN: ${{ secrets.PRIVATE_REPOSITORY_ACCESS }}

        - name: Install dependencies
          uses: ramsey/composer-install@v2
          with:
            dependency-versions: "${{ matrix.dependencies }}"

        - name: Install tools
          uses: ramsey/composer-install@v2
          with:
            working-directory: ./tools

        - name: Static Analyze
          run: composer test:mutation
          timeout-minutes: 2